site_name: Product Engineering
theme:
  name: mkdocs
  color_mode: dark
  nav_style: dark

docs_dir: product-engineering
# Waiting to hear back from pending issue request:
# https://github.com/LukeCarrier/mkdocs-drawio-exporter/issues/83
# plugins:
# - drawio-exporter
