import requests
import openai
import os
import subprocess

# --- Configuration ---
GITHUB_TOKEN = "your_github_token"
GITHUB_REPO = "owner/repo"  # Example: "octocat/Hello-World"
ISSUE_NUMBER = 1  # Change to the issue number you want to process
BRANCH_NAME = f"ai-fix-{ISSUE_NUMBER}"
OPENAI_API_KEY = "your_openai_api_key"


def get_github_issue():
    url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{ISSUE_NUMBER}"
    headers = {"Authorization": f"token {GITHUB_TOKEN}"}
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        issue = response.json()
        return issue["title"], issue["body"]
    else:
        print("Failed to fetch issue:", response.json())
        return None, None


def generate_code(issue_title, issue_body):
    prompt = f"""Issue Title: {issue_title}\nIssue Description: {issue_body}\n\nGenerate a Python solution for this issue."""
    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "You are an expert software engineer."},
            {"role": "user", "content": prompt},
        ],
    )
    return response["choices"][0]["message"]["content"]


def create_new_branch():
    subprocess.run(["git", "checkout", "-b", BRANCH_NAME])


def commit_and_push_changes(code):
    with open("generated_fix.py", "w") as f:
        f.write(code)

    subprocess.run(["git", "add", "generated_fix.py"])
    subprocess.run(
        ["git", "commit", "-m", f"AI-generated fix for issue #{ISSUE_NUMBER}"]
    )
    subprocess.run(["git", "push", "origin", BRANCH_NAME])


def create_pull_request():
    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
    }
    data = {
        "title": f"AI Fix for Issue #{ISSUE_NUMBER}",
        "head": BRANCH_NAME,
        "base": "main",
        "body": "This pull request was automatically generated by AI. Please review.",
    }
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 201:
        print("Pull request created successfully:", response.json()["html_url"])
    else:
        print("Failed to create pull request:", response.json())


# --- Workflow Execution ---
if __name__ == "__main__":
    title, body = get_github_issue()
    if title and body:
        print("Generating AI fix...")
        code = generate_code(title, body)
        print("Creating new branch...")
        create_new_branch()
        print("Committing and pushing changes...")
        commit_and_push_changes(code)
        print("Creating pull request...")
        create_pull_request()
    else:
        print("Failed to process issue.")
